CytronBabitchBundle_Game:
    resource: "@CytronBabitchBundle/Controller/GameController.php"
    type:     rest

CytronBabitchBundle_Player:
    resource: "@CytronBabitchBundle/Controller/PlayerController.php"
    type:     rest

CytronBabitchBundle_Team:
    resource: "@CytronBabitchBundle/Controller/TeamController.php"
    type:     rest

CytronBabitchBundle_Tournament:
    resource: "@CytronBabitchBundle/Resources/config/tournament_routes.yml"
    type:     rest

# CytronBabitchBundle_TournamentGroup:
#     resource: "@CytronBabitchBundle/Controller/TournamentGroupController.php"
#     parent: CytronBabitchBundle_Tournament
#     type: rest
